name: Build and push latest dev version to dockerhub

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  DH_USER: ""
  DH_PASS: ""

jobs:
  build-images:

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build images
        run: |
          echo "Building images"
          docker build -t z100/vayan:latest .

      - name: Push images
        run: |
          echo "Login to dockerhub"
          docker login -u ${{ secrets.DH_USER }} -p ${{ secrets.DH_PASS }}

          echo "Pushing images"
          docker push z100/vayan:latest
